-- ==============================================================================
-- SISTEMA CARNICERÍA MARÍA - MIGRACIÓN DE PAQUETES Y PESO
-- Ejecutar este script en el SQL Editor de Supabase.
-- ==============================================================================

-- 1. MODIFICAR TABLA PRODUCTOS
ALTER TABLE public.productos 
ADD COLUMN IF NOT EXISTS tipo_venta TEXT DEFAULT 'UNIDAD' CHECK (tipo_venta IN ('PESO', 'UNIDAD', 'PAQUETE'));

ALTER TABLE public.productos 
ADD COLUMN IF NOT EXISTS stock_granel NUMERIC DEFAULT 0 CHECK (stock_granel >= 0);

ALTER TABLE public.productos 
ADD COLUMN IF NOT EXISTS stock_empacado NUMERIC DEFAULT 0 CHECK (stock_empacado >= 0);

-- 1.B MODIFICAR TABLA COMPRAS (purchase_orders) PARA AGREGAR COLUMNAS FALTANTES
ALTER TABLE public.purchase_orders ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.purchase_orders ADD COLUMN IF NOT EXISTS supplier_phone TEXT;
ALTER TABLE public.purchase_orders ADD COLUMN IF NOT EXISTS supplier_email TEXT;
ALTER TABLE public.purchase_orders ADD COLUMN IF NOT EXISTS number BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 1.C MODIFICAR TABLA VENTAS (sales_orders) PARA AGREGAR COLUMNAS FALTANTES Y LOGICA DE TOTALES
ALTER TABLE public.sales_orders ADD COLUMN IF NOT EXISTS customer_email TEXT;
ALTER TABLE public.sales_orders ADD COLUMN IF NOT EXISTS customer_phone TEXT;
ALTER TABLE public.sales_orders ADD COLUMN IF NOT EXISTS discount_total NUMERIC DEFAULT 0;
ALTER TABLE public.sales_orders ADD COLUMN IF NOT EXISTS tax_total NUMERIC DEFAULT 0;

-- Trigger para sincronizar campos de totales (discount <=> discount_total, tax <=> tax_total)
CREATE OR REPLACE FUNCTION public.sync_sales_order_totals()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.discount_total IS NOT NULL THEN
        NEW.discount := NEW.discount_total;
    ELSIF NEW.discount IS NOT NULL THEN
        NEW.discount_total := NEW.discount;
    END IF;

    IF NEW.tax_total IS NOT NULL THEN
        NEW.tax := NEW.tax_total;
    ELSIF NEW.tax IS NOT NULL THEN
        NEW.tax_total := NEW.tax;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS trg_sync_sales_order_totals ON public.sales_orders;
CREATE TRIGGER trg_sync_sales_order_totals
BEFORE INSERT OR UPDATE ON public.sales_orders
FOR EACH ROW EXECUTE FUNCTION public.sync_sales_order_totals();

-- Migrar stocks existentes a stock_granel
UPDATE public.productos 
SET stock_granel = stock 
WHERE stock_granel = 0 AND stock > 0;

-- Trigger para sincronizar stock = stock_granel + stock_empacado
CREATE OR REPLACE FUNCTION public.sync_total_stock()
RETURNS TRIGGER AS $$
BEGIN
    NEW.stock = COALESCE(NEW.stock_granel, 0) + COALESCE(NEW.stock_empacado, 0);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS trg_sync_total_stock ON public.productos;
CREATE TRIGGER trg_sync_total_stock
BEFORE INSERT OR UPDATE ON public.productos
FOR EACH ROW EXECUTE FUNCTION public.sync_total_stock();

-- 2. CREAR TABLA LOTES
CREATE TABLE IF NOT EXISTS public.lotes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo_lote TEXT NOT NULL UNIQUE,
    codigo_caja TEXT,
    producto_id UUID REFERENCES public.productos(id) ON DELETE CASCADE,
    peso_recibido NUMERIC NOT NULL CHECK (peso_recibido >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CREAR TABLA PAQUETES
CREATE TABLE IF NOT EXISTS public.paquetes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    producto_id UUID NOT NULL REFERENCES public.productos(id) ON DELETE CASCADE,
    lote_id UUID REFERENCES public.lotes(id) ON DELETE SET NULL,
    sub_codigo TEXT NOT NULL UNIQUE,
    codigo_barras TEXT NOT NULL UNIQUE,
    peso NUMERIC NOT NULL CHECK (peso > 0),
    precio_por_unidad NUMERIC NOT NULL CHECK (precio_por_unidad >= 0),
    precio_total NUMERIC NOT NULL CHECK (precio_total >= 0),
    fecha_empaque TIMESTAMPTZ DEFAULT NOW(),
    fecha_vencimiento TIMESTAMPTZ,
    estado TEXT DEFAULT 'DISPONIBLE' CHECK (estado IN ('DISPONIBLE', 'VENDIDO', 'ANULADO', 'DEVUELTO', 'MERMA')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar disparador updated_at en paquetes
DROP TRIGGER IF EXISTS trg_paquetes_updated_at ON public.paquetes;
CREATE TRIGGER trg_paquetes_updated_at BEFORE UPDATE ON public.paquetes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Secuencia para códigos incrementales
CREATE SEQUENCE IF NOT EXISTS public.paquete_seq START WITH 1;

-- 4. MODIFICAR DETALLES DE VENTA
ALTER TABLE public.sales_order_items 
ADD COLUMN IF NOT EXISTS package_id UUID REFERENCES public.paquetes(id) ON DELETE SET NULL;

-- 5. HABILITAR SEGURIDAD RLS EN NUEVAS TABLAS
ALTER TABLE public.lotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paquetes ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad para Lotes
DROP POLICY IF EXISTS "lotes_read" ON public.lotes;
CREATE POLICY "lotes_read" ON public.lotes FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "lotes_insert" ON public.lotes;
CREATE POLICY "lotes_insert" ON public.lotes FOR INSERT TO authenticated WITH CHECK (public.is_staff());

DROP POLICY IF EXISTS "lotes_delete" ON public.lotes;
CREATE POLICY "lotes_delete" ON public.lotes FOR DELETE TO authenticated USING (public.is_admin());

-- Políticas de seguridad para Paquetes
DROP POLICY IF EXISTS "paquetes_read" ON public.paquetes;
CREATE POLICY "paquetes_read" ON public.paquetes FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "paquetes_insert" ON public.paquetes;
CREATE POLICY "paquetes_insert" ON public.paquetes FOR INSERT TO authenticated WITH CHECK (public.is_staff());

DROP POLICY IF EXISTS "paquetes_update" ON public.paquetes;
CREATE POLICY "paquetes_update" ON public.paquetes FOR UPDATE TO authenticated USING (public.is_staff());

DROP POLICY IF EXISTS "paquetes_delete" ON public.paquetes;
CREATE POLICY "paquetes_delete" ON public.paquetes FOR DELETE TO authenticated USING (public.is_admin());

-- ==============================================================================
-- 6. CREACIÓN DE RPC Y FUNCIONES AUTOMÁTICAS
-- ==============================================================================

-- A. Crear paquete atómicamente desde producto a granel
CREATE OR REPLACE FUNCTION public.fn_crear_paquete(
    p_producto_id UUID,
    p_lote_id UUID,
    p_peso NUMERIC,
    p_precio_por_unidad NUMERIC,
    p_fecha_empaque TIMESTAMPTZ,
    p_fecha_vencimiento TIMESTAMPTZ,
    p_descontar_granel BOOLEAN DEFAULT TRUE
) RETURNS JSONB AS $$
DECLARE
    v_seq BIGINT;
    v_sub_codigo TEXT;
    v_codigo_barras TEXT;
    v_precio_total NUMERIC;
    v_paquete public.paquetes;
BEGIN
    -- 1. Validar que exista suficiente stock a granel (si p_descontar_granel es TRUE)
    IF p_descontar_granel AND NOT EXISTS (
        SELECT 1 FROM public.productos 
        WHERE id = p_producto_id AND stock_granel >= p_peso
    ) THEN
        RAISE EXCEPTION 'INSUFFICIENT_BULK_STOCK';
    END IF;

    -- 2. Generar sub_codigo y barcode incremental
    v_seq := nextval('public.paquete_seq');
    v_sub_codigo := 'PAQ-' || lpad(v_seq::text, 6, '0');
    v_codigo_barras := '2' || lpad(v_seq::text, 11, '0');
    v_precio_total := round(p_peso * p_precio_por_unidad, 2);

    -- 3. Actualizar stock del producto
    IF p_descontar_granel THEN
        UPDATE public.productos
        SET stock_granel = stock_granel - p_peso,
            stock_empacado = stock_empacado + p_peso
        WHERE id = p_producto_id;
    ELSE
        UPDATE public.productos
        SET stock_empacado = stock_empacado + p_peso
        WHERE id = p_producto_id;
    END IF;

    -- 4. Registrar paquete físico
    INSERT INTO public.paquetes (
        producto_id, lote_id, sub_codigo, codigo_barras, peso, precio_por_unidad, precio_total, fecha_empaque, fecha_vencimiento, estado
    ) VALUES (
        p_producto_id, p_lote_id, v_sub_codigo, v_codigo_barras, p_peso, p_precio_por_unidad, v_precio_total, COALESCE(p_fecha_empaque, NOW()), p_fecha_vencimiento, 'DISPONIBLE'
    ) RETURNING * INTO v_paquete;

    -- 5. Guardar movimiento de inventario (Kardex)
    INSERT INTO public.inventario_movimientos (
        producto_id, producto_nombre, tipo, cantidad, stock_anterior, stock_nuevo, motivo
    )
    SELECT 
        p_producto_id, 
        p.nombre, 
        'ajuste', 
        p_peso, 
        p.stock,
        p.stock, 
        'Empaquetado - Paquete ' || v_sub_codigo
    FROM public.productos p
    WHERE p.id = p_producto_id;

    RETURN to_jsonb(v_paquete);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- B. Devolución de paquete vendido
CREATE OR REPLACE FUNCTION public.fn_devolver_paquete(
    p_paquete_id UUID,
    p_destino_estado TEXT
) RETURNS JSONB AS $$
DECLARE
    v_pkg public.paquetes;
    v_prod public.productos;
    v_stock_anterior NUMERIC;
    v_stock_nuevo NUMERIC;
BEGIN
    SELECT * INTO v_pkg FROM public.paquetes WHERE id = p_paquete_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'PACKAGE_NOT_FOUND';
    END IF;

    IF v_pkg.estado <> 'VENDIDO' THEN
        RAISE EXCEPTION 'PACKAGE_NOT_SOLD';
    END IF;

    -- Actualizar estado a DISPONIBLE o MERMA
    UPDATE public.paquetes
    SET estado = p_destino_estado,
        updated_at = NOW()
    WHERE id = p_paquete_id;

    IF p_destino_estado = 'DISPONIBLE' THEN
        SELECT * INTO v_prod FROM public.productos WHERE id = v_pkg.producto_id FOR UPDATE;
        v_stock_anterior := v_prod.stock;

        UPDATE public.productos
        SET stock_empacado = stock_empacado + v_pkg.peso
        WHERE id = v_pkg.producto_id;

        SELECT stock INTO v_stock_nuevo FROM public.productos WHERE id = v_pkg.producto_id;

        INSERT INTO public.inventario_movimientos (
            producto_id, producto_nombre, tipo, cantidad, stock_anterior, stock_nuevo, motivo
        ) VALUES (
            v_pkg.producto_id, v_prod.nombre, 'entrada', v_pkg.peso, v_stock_anterior, v_stock_nuevo, 'Devolución - Reingreso a Inventario - Paquete ' || v_pkg.sub_codigo
        );
    ELSE
        -- Si es MERMA, el stock se mantiene restado
        SELECT * INTO v_prod FROM public.productos WHERE id = v_pkg.producto_id;
        INSERT INTO public.inventario_movimientos (
            producto_id, producto_nombre, tipo, cantidad, stock_anterior, stock_nuevo, motivo
        ) VALUES (
            v_pkg.producto_id, v_prod.nombre, 'salida', v_pkg.peso, v_prod.stock, v_prod.stock, 'Devolución - Registrado como Merma - Paquete ' || v_pkg.sub_codigo
        );
    END IF;

    SELECT * INTO v_pkg FROM public.paquetes WHERE id = p_paquete_id;
    RETURN to_jsonb(v_pkg);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- C. Registrar merma de un paquete disponible
CREATE OR REPLACE FUNCTION public.fn_registrar_merma_paquete(
    p_paquete_id UUID,
    p_motivo TEXT
) RETURNS JSONB AS $$
DECLARE
    v_pkg public.paquetes;
    v_prod public.productos;
    v_stock_anterior NUMERIC;
    v_stock_nuevo NUMERIC;
BEGIN
    SELECT * INTO v_pkg FROM public.paquetes WHERE id = p_paquete_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'PACKAGE_NOT_FOUND';
    END IF;
    IF v_pkg.estado <> 'DISPONIBLE' THEN
        RAISE EXCEPTION 'PACKAGE_NOT_AVAILABLE';
    END IF;

    UPDATE public.paquetes
    SET estado = 'MERMA',
        updated_at = NOW()
    WHERE id = p_paquete_id;

    -- Descontar stock empacado
    SELECT * INTO v_prod FROM public.productos WHERE id = v_pkg.producto_id FOR UPDATE;
    v_stock_anterior := v_prod.stock;

    UPDATE public.productos
    SET stock_empacado = stock_empacado - v_pkg.peso
    WHERE id = v_pkg.producto_id;

    SELECT stock INTO v_stock_nuevo FROM public.productos WHERE id = v_pkg.producto_id;

    INSERT INTO public.inventario_movimientos (
        producto_id, producto_nombre, tipo, cantidad, stock_anterior, stock_nuevo, motivo
    ) VALUES (
        v_pkg.producto_id, v_prod.nombre, 'salida', v_pkg.peso, v_stock_anterior, v_stock_nuevo, 'Merma - Paquete ' || v_pkg.sub_codigo || ' - Motivo: ' || COALESCE(p_motivo, 'No especificado')
    );

    SELECT * INTO v_pkg FROM public.paquetes WHERE id = p_paquete_id;
    RETURN to_jsonb(v_pkg);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- D. Actualizar finalización de venta (Descuento de inventario robusto)
CREATE OR REPLACE FUNCTION public.fn_finalize_order(p_order_id UUID)
RETURNS JSONB AS $$
DECLARE
    v_order public.sales_orders;
    v_item RECORD;
    v_pkg public.paquetes;
    v_prod public.productos;
    v_stock_anterior NUMERIC;
    v_stock_nuevo NUMERIC;
BEGIN
    SELECT * INTO v_order FROM public.sales_orders WHERE id = p_order_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'ORDER_NOT_FOUND';
    END IF;

    IF v_order.status = 'paid' THEN
        RETURN to_jsonb(v_order);
    END IF;

    FOR v_item IN SELECT * FROM public.sales_order_items WHERE order_id = p_order_id LOOP
        IF v_item.package_id IS NOT NULL THEN
            -- Venta de paquete físico
            SELECT * INTO v_pkg FROM public.paquetes WHERE id = v_item.package_id FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'PACKAGE_NOT_FOUND %', v_item.product_name;
            END IF;
            IF v_pkg.estado <> 'DISPONIBLE' THEN
                RAISE EXCEPTION 'PACKAGE_ALREADY_SOLD %', v_item.product_name;
            END IF;

            -- Registrar venta de paquete
            UPDATE public.paquetes
            SET estado = 'VENDIDO',
                updated_at = NOW()
            WHERE id = v_pkg.id;

            -- Descontar del stock empacado
            SELECT * INTO v_prod FROM public.productos WHERE id = v_pkg.producto_id FOR UPDATE;
            v_stock_anterior := v_prod.stock;
            
            UPDATE public.productos
            SET stock_empacado = stock_empacado - v_pkg.peso
            WHERE id = v_pkg.producto_id
            RETURNING stock INTO v_stock_nuevo;

            INSERT INTO public.inventario_movimientos (
                producto_id, producto_nombre, tipo, cantidad, stock_anterior, stock_nuevo, motivo
            ) VALUES (
                v_pkg.producto_id, v_prod.nombre, 'salida', v_pkg.peso, v_stock_anterior, v_stock_nuevo, 'Venta - Paquete ' || v_pkg.sub_codigo || ' - Factura #' || p_order_id
            );

        ELSIF v_item.product_id IS NOT NULL THEN
            -- Venta normal por unidad o peso a granel
            SELECT * INTO v_prod FROM public.productos WHERE id = v_item.product_id FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'PRODUCT_NOT_FOUND';
            END IF;
            
            -- Validar contra stock_granel
            IF v_prod.stock_granel < v_item.qty THEN
                RAISE EXCEPTION 'INSUFFICIENT_STOCK for product % (need %, have %)', v_prod.id, v_item.qty, v_prod.stock_granel;
            END IF;

            v_stock_anterior := v_prod.stock;

            -- Descontar de granel
            UPDATE public.productos
            SET stock_granel = stock_granel - v_item.qty
            WHERE id = v_item.product_id;

            SELECT stock INTO v_stock_nuevo FROM public.productos WHERE id = v_item.product_id;

            INSERT INTO public.inventario_movimientos (
                producto_id, producto_nombre, tipo, cantidad, stock_anterior, stock_nuevo, motivo
            ) VALUES (
                v_item.product_id, v_prod.nombre, 'salida', v_item.qty, v_stock_anterior, v_stock_nuevo, 'Venta - Factura #' || p_order_id
            );
        END IF;
    END LOOP;

    -- Finalizar la factura
    UPDATE public.sales_orders
    SET status = 'paid',
        paid_at = NOW()
    WHERE id = p_order_id
    RETURNING * INTO v_order;

    RETURN to_jsonb(v_order);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- E. Actualizar cancelación de venta (Reversión robusta)
CREATE OR REPLACE FUNCTION public.fn_cancel_order(p_order_id UUID)
RETURNS JSONB AS $$
DECLARE
    v_order public.sales_orders;
    v_item RECORD;
    v_pkg public.paquetes;
    v_prod public.productos;
    v_stock_anterior NUMERIC;
    v_stock_nuevo NUMERIC;
BEGIN
    SELECT * INTO v_order FROM public.sales_orders WHERE id = p_order_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'ORDER_NOT_FOUND';
    END IF;

    IF v_order.status = 'cancelled' THEN
        RETURN to_jsonb(v_order);
    END IF;

    FOR v_item IN SELECT * FROM public.sales_order_items WHERE order_id = p_order_id LOOP
        IF v_item.package_id IS NOT NULL THEN
            -- Cancelación de paquete vendido
            SELECT * INTO v_pkg FROM public.paquetes WHERE id = v_item.package_id FOR UPDATE;
            IF FOUND THEN
                UPDATE public.paquetes
                SET estado = 'DISPONIBLE',
                    updated_at = NOW()
                WHERE id = v_pkg.id;

                SELECT * INTO v_prod FROM public.productos WHERE id = v_pkg.producto_id FOR UPDATE;
                v_stock_anterior := v_prod.stock;

                UPDATE public.productos
                SET stock_empacado = stock_empacado + v_pkg.peso
                WHERE id = v_pkg.producto_id
                RETURNING stock INTO v_stock_nuevo;

                INSERT INTO public.inventario_movimientos (
                    producto_id, producto_nombre, tipo, cantidad, stock_anterior, stock_nuevo, motivo
                ) VALUES (
                    v_pkg.producto_id, v_prod.nombre, 'entrada', v_pkg.peso, v_stock_anterior, v_stock_nuevo, 'Cancelación de Venta - Paquete ' || v_pkg.sub_codigo || ' - Factura #' || p_order_id
                );
            END IF;
        ELSIF v_item.product_id IS NOT NULL THEN
            -- Cancelación de venta de producto normal o granel
            SELECT * INTO v_prod FROM public.productos WHERE id = v_item.product_id FOR UPDATE;
            IF FOUND THEN
                v_stock_anterior := v_prod.stock;

                UPDATE public.productos
                SET stock_granel = stock_granel + v_item.qty
                WHERE id = v_item.product_id;

                SELECT stock INTO v_stock_nuevo FROM public.productos WHERE id = v_item.product_id;

                INSERT INTO public.inventario_movimientos (
                    producto_id, producto_nombre, tipo, cantidad, stock_anterior, stock_nuevo, motivo
                ) VALUES (
                    v_item.product_id, v_prod.nombre, 'entrada', v_item.qty, v_stock_anterior, v_stock_nuevo, 'Cancelación de Venta - Factura #' || p_order_id
                );
            END IF;
        END IF;
    END LOOP;

    -- Cancelar la factura
    UPDATE public.sales_orders
    SET status = 'cancelled'
    WHERE id = p_order_id
    RETURNING * INTO v_order;

    RETURN to_jsonb(v_order);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- F. Actualizar finalización de compra (Ingresa a stock_granel)
CREATE OR REPLACE FUNCTION public.finalize_purchase_batch(p_purchase_id UUID)
RETURNS JSONB AS $$
DECLARE
    v_item RECORD;
    v_stock_actual NUMERIC;
    v_stock_nuevo NUMERIC;
    v_purchase public.purchase_orders;
BEGIN
    FOR v_item IN SELECT * FROM public.purchase_order_items WHERE purchase_id = p_purchase_id LOOP
        IF v_item.product_id IS NOT NULL AND v_item.qty > 0 THEN
            SELECT stock_granel INTO v_stock_actual FROM public.productos WHERE id = v_item.product_id FOR UPDATE;
            
            IF FOUND THEN
                v_stock_actual := COALESCE(v_stock_actual, 0);
                v_stock_nuevo := v_stock_actual + v_item.qty;

                UPDATE public.productos
                SET stock_granel = v_stock_nuevo
                WHERE id = v_item.product_id;

                -- Consultamos el nuevo total calculado por el trigger
                SELECT stock INTO v_stock_nuevo FROM public.productos WHERE id = v_item.product_id;

                INSERT INTO public.inventario_movimientos (
                    producto_id, producto_nombre, tipo, cantidad, stock_anterior, stock_nuevo, motivo
                ) VALUES (
                    v_item.product_id, v_item.product_name, 'entrada', v_item.qty, v_stock_actual, v_stock_nuevo, 'Compra - Orden #' || p_purchase_id
                );
            END IF;
        END IF;
    END LOOP;

    UPDATE public.purchase_orders
    SET status = 'completed',
        completed_at = NOW()
    WHERE id = p_purchase_id
    RETURNING * INTO v_purchase;

    RETURN to_jsonb(v_purchase);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
